# Generated by Django 5.2.7 on 2025-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staffs/'),
        ),
    ]
