# Generated by Django 5.2.7 on 2025-11-04 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='lunch_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pickup_authorized',
            field=models.TextField(blank=True, help_text='Comma-separated list of authorized pickup persons'),
        ),
        migrations.AddField(
            model_name='student',
            name='relationship',
            field=models.CharField(blank=True, help_text='e.g., Mother, Father, Aunt', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
