# Generated by Django 3.0.5 on 2020-05-06 14:20

from django.db import migrations


def default_site_config(apps, schema_editor):
    """Default site configurations"""

    # Use the historical User model from the migration system
    User = apps.get_model('auth', 'User')

    # Create superuser if not exists
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser("admin", "admin@schoolapp.com", "admin123")

    # SiteConfig entries
    Config = apps.get_model("corecode", "SiteConfig")
    for key, value in [
        ("school_name", "My School"),
        ("school_slogan", "A great school"),
        ("school_address", "Lagos, Nigeria"),
    ]:
        Config.objects.get_or_create(key=key, defaults={"value": value})

    # AcademicSession
    Session = apps.get_model("corecode", "AcademicSession")
    Session.objects.get_or_create(name="2019/2020", defaults={"current": True})

    # AcademicTerm
    Term = apps.get_model("corecode", "AcademicTerm")
    for name, current in [
        ("1st Term", True),
        ("2nd Term", False),
        ("3rd Term", False),
    ]:
        Term.objects.get_or_create(name=name, defaults={"current": current})

    # Subjects
    Subject = apps.get_model("corecode", "Subject")
    for name in ["Mathematics", "English"]:
        Subject.objects.get_or_create(name=name)

    # Student Classes
    StudentClass = apps.get_model("corecode", "StudentClass")
    for name in ["JSS 1", "JSS 2"]:
        StudentClass.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    atomic = False  # prevents TransactionManagementError

    dependencies = [
        ('corecode', '0001_initial'),
        ('auth', '0001_initial'),  # Ensure auth tables exist first
    ]

    operations = [
        migrations.RunPython(default_site_config),
    ]
