# Generated by Django 5.2.7 on 2025-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='questions',
            field=models.TextField(blank=True, help_text='Enter homework questions (one per line or numbered)'),
        ),
    ]
