# Generated by Django 5.2.7 on 2025-11-24 06:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_device_id_student_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('code', 'Code'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='portfolio/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])])),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('code_file', models.FileField(blank=True, null=True, upload_to='portfolio/code/', validators=[django.core.validators.FileExtensionValidator(['py', 'js', 'java', 'cpp', 'html', 'css'])])),
                ('external_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('skills_used', models.CharField(blank=True, help_text='Comma-separated skills', max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_portfolio.portfoliocategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
