# Generated by Django 5.2.7 on 2025-11-06 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('corecode', '0005_alter_academicsession_id_alter_academicterm_id_and_more'),
        ('students', '0003_student_allergies_student_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceentry',
            options={'ordering': ('student__surname', 'student__firstname'), 'verbose_name_plural': 'Attendance entries'},
        ),
        migrations.AlterModelOptions(
            name='attendanceregister',
            options={'ordering': ('-date',), 'permissions': [('can_lock_register', 'Can lock attendance register'), ('can_bulk_create', 'Can bulk create registers')]},
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused'), ('H', 'Half Day')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='DailyAttendanceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_create', models.BooleanField(default=True)),
                ('notify_absent', models.BooleanField(default=True)),
                ('absent_threshold', models.PositiveIntegerField(default=3, help_text='Notify after consecutive absences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('days_late', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm')),
            ],
            options={
                'verbose_name_plural': 'Attendance summaries',
                'unique_together': {('student', 'term', 'session')},
            },
        ),
    ]
