# Generated by Django 5.2.7 on 2025-11-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_allergies_student_emergency_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('school_logo_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right')], default='top_center', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='idcards/barcodes/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='idcards/qrcodes/')),
                ('template_used', models.CharField(default='default', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Student ID Card',
                'verbose_name_plural': 'Student ID Cards',
            },
        ),
    ]
