# Generated by Django 5.2.7 on 2025-11-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0001_initial'),
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('template_used', models.CharField(default='default', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='teacher_qrcodes/')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
            options={
                'verbose_name': 'Teacher ID Card',
                'verbose_name_plural': 'Teacher ID Cards',
            },
        ),
    ]
